# Generated by Django 5.0.4 on 2024-09-30 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 14, 5, 41, 131369, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
