# Generated by Django 5.0.4 on 2024-09-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='tbl_contact',
        ),
    ]
