# Generated by Django 5.0.4 on 2024-10-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0004_rename_contact_tbl_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile_pic',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
