# Generated by Django 5.0.4 on 2024-10-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0007_usm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usm',
            new_name='tbl_Usm',
        ),
    ]
