# Generated by Django 5.0.4 on 2024-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0009_upload_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Assignment',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('new_file', models.FileField(upload_to='myimage')),
            ],
        ),
    ]
