# Generated by Django 5.0.4 on 2024-10-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0010_upload_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('comp', models.CharField(max_length=500)),
                ('reqdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('feed', models.CharField(max_length=500)),
                ('reqdate', models.DateTimeField()),
            ],
        ),
    ]
