# Generated by Django 5.0.4 on 2024-10-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0012_feedback_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='program',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
