# Generated by Django 5.0.4 on 2024-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0013_complaints_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_noti',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('notif', models.CharField(max_length=200)),
                ('notireg', models.DateTimeField()),
            ],
        ),
    ]
