# Generated by Django 5.0.4 on 2024-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0014_tbl_noti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_assignment',
            name='new_file',
            field=models.FileField(blank=True, upload_to='myimage'),
        ),
    ]
