# Generated by Django 5.0.4 on 2024-10-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0016_alter_upload_assignment_new_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_assignment',
            name='new_file',
            field=models.FileField(default=1, upload_to='myimage'),
            preserve_default=False,
        ),
    ]
